// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafeBit.Api.Data;

#nullable disable

namespace SafeBit.Api.Migrations
{
    [DbContext(typeof(SafeBiteDbContext))]
    [Migration("20260126195505_AddLogoutSupport")]
    partial class AddLogoutSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("safebit")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafeBit.Api.Model.Allergy", b =>
                {
                    b.Property<int>("AllergyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AllergyID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("AllergyID");

                    b.ToTable("Allergies", "safebit");

                    b.HasData(
                        new
                        {
                            AllergyID = 1,
                            Category = "Food",
                            CreatedAt = new DateTime(2026, 1, 26, 19, 55, 5, 552, DateTimeKind.Utc).AddTicks(6981),
                            IsDeleted = false,
                            Name = "Peanuts"
                        },
                        new
                        {
                            AllergyID = 2,
                            Category = "Dairy",
                            CreatedAt = new DateTime(2026, 1, 26, 19, 55, 5, 552, DateTimeKind.Utc).AddTicks(6984),
                            IsDeleted = false,
                            Name = "Milk"
                        },
                        new
                        {
                            AllergyID = 3,
                            Category = "Food",
                            CreatedAt = new DateTime(2026, 1, 26, 19, 55, 5, 552, DateTimeKind.Utc).AddTicks(6985),
                            IsDeleted = false,
                            Name = "Eggs"
                        },
                        new
                        {
                            AllergyID = 4,
                            Category = "Food",
                            CreatedAt = new DateTime(2026, 1, 26, 19, 55, 5, 552, DateTimeKind.Utc).AddTicks(6986),
                            IsDeleted = false,
                            Name = "Seafood"
                        });
                });

            modelBuilder.Entity("SafeBit.Api.Model.Disease", b =>
                {
                    b.Property<int>("DiseaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiseaseID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("DiseaseID");

                    b.ToTable("Diseases", "safebit");

                    b.HasData(
                        new
                        {
                            DiseaseID = 1,
                            Category = "Chronic",
                            CreatedAt = new DateTime(2026, 1, 26, 19, 55, 5, 552, DateTimeKind.Utc).AddTicks(6998),
                            IsDeleted = false,
                            Name = "Diabetes"
                        },
                        new
                        {
                            DiseaseID = 2,
                            Category = "Digestive",
                            CreatedAt = new DateTime(2026, 1, 26, 19, 55, 5, 552, DateTimeKind.Utc).AddTicks(6999),
                            IsDeleted = false,
                            Name = "Celiac Disease"
                        },
                        new
                        {
                            DiseaseID = 3,
                            Category = "Chronic",
                            CreatedAt = new DateTime(2026, 1, 26, 19, 55, 5, 552, DateTimeKind.Utc).AddTicks(7000),
                            IsDeleted = false,
                            Name = "Hypertension"
                        });
                });

            modelBuilder.Entity("SafeBit.Api.Model.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleID");

                    b.ToTable("Roles", "safebit");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Type = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            Type = "User"
                        });
                });

            modelBuilder.Entity("SafeBit.Api.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserID");

                    b.ToTable("Users", "safebit");
                });

            modelBuilder.Entity("SafeBit.Api.Model.UserAllergy", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("AllergyID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("UserID", "AllergyID");

                    b.ToTable("UserAllergies", "safebit");
                });

            modelBuilder.Entity("SafeBit.Api.Model.UserDisease", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("DiseaseID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("UserID", "DiseaseID");

                    b.ToTable("UserDiseases", "safebit");
                });
#pragma warning restore 612, 618
        }
    }
}
